.editorconfig, .eslintrc, .gitignore, CHANGELOG.md, CONTRIBUTING.md, Jenkinsfile, LICENSE, README.md, findInterfaces/FindInterfacesContainer.css, findInterfaces/FindInterfacesContainer.js, findInterfaces/index.js, index.js, package.json, translations/ui-plugin-find-interface/en.json
=> UIORGS-35 project setup

findInterfaces/FindInterfacesContainer.js, findInterfaces/FindInterfacesModal.css, findInterfaces/FindInterfacesModal.js, translations/ui-plugin-find-interface/en.json
=> UIORGS-35 assign interfaces - find interfaces modal

translations/ui-plugin-find-interface/ar.json, translations/ui-plugin-find-interface/ca.json, translations/ui-plugin-find-interface/da.json, translations/ui-plugin-find-interface/de.json, translations/ui-plugin-find-interface/en_GB.json, translations/ui-plugin-find-interface/en_SE.json, translations/ui-plugin-find-interface/en_US.json, translations/ui-plugin-find-interface/es.json, translations/ui-plugin-find-interface/es_419.json, translations/ui-plugin-find-interface/es_ES.json, translations/ui-plugin-find-interface/fr.json, translations/ui-plugin-find-interface/fr_FR.json, translations/ui-plugin-find-interface/hu.json, translations/ui-plugin-find-interface/it_IT.json, translations/ui-plugin-find-interface/pt_BR.json, translations/ui-plugin-find-interface/pt_PT.json, translations/ui-plugin-find-interface/zh_CN.json
=> Update translation strings as of 20190513T134002

findInterfaces/FindInterfacesModal.css, findInterfaces/FindInterfacesModal.js, translations/ui-plugin-find-interface/en.json
=> UIORGS-35 assign interfaces - select several

findInterfaces/FindInterfacesFilters.js, findInterfaces/FindInterfacesModal.js, findInterfaces/constants.js, translations/ui-plugin-find-interface/en.json
=> UIORGS-35 assign interface - fitlers

Jenkinsfile, findInterfaces/FindInterfacesContainer.js, findInterfaces/FindInterfacesModal.js, test/bigtest/.eslintrc, test/bigtest/helpers/PluginHarness.js, test/bigtest/helpers/helpers.js, test/bigtest/index.js, test/bigtest/interactors/application.js, test/bigtest/interactors/findInterfaces.js, test/bigtest/network/boot.js, test/bigtest/network/config.js, test/bigtest/network/configs/interfaces.js, test/bigtest/network/factories/interface.js, test/bigtest/network/index.js, test/bigtest/network/models/interface.js, test/bigtest/network/serializers/base.js, test/bigtest/network/serializers/interface.js, test/bigtest/tests/findInterfaces.e2e.js
=> UIORGS-35 find interfaces unit tests

findInterfaces/FindInterfacesFilters.js, findInterfaces/FindInterfacesModal.js, findInterfaces/constants.js, package.json, test/bigtest/interactors/findInterfaces.js, test/bigtest/tests/findInterfaces.e2e.js
=> UIORGS-35 find interfaces - unit tests

findInterfaces/FindInterfacesModal.css, findInterfaces/FindInterfacesModal.js
=> UIORGS-35 assign interfaces - column style

translations/ui-plugin-find-interface/ar.json, translations/ui-plugin-find-interface/ca.json, translations/ui-plugin-find-interface/da.json, translations/ui-plugin-find-interface/de.json, translations/ui-plugin-find-interface/en_GB.json, translations/ui-plugin-find-interface/en_SE.json, translations/ui-plugin-find-interface/en_US.json, translations/ui-plugin-find-interface/es.json, translations/ui-plugin-find-interface/es_419.json, translations/ui-plugin-find-interface/es_ES.json, translations/ui-plugin-find-interface/fr.json, translations/ui-plugin-find-interface/fr_FR.json, translations/ui-plugin-find-interface/hu.json, translations/ui-plugin-find-interface/it_IT.json, translations/ui-plugin-find-interface/pt_BR.json, translations/ui-plugin-find-interface/pt_PT.json, translations/ui-plugin-find-interface/zh_CN.json
=> Update translation strings as of 20190517T183537

translations/ui-plugin-find-interface/es.json, translations/ui-plugin-find-interface/es_419.json, translations/ui-plugin-find-interface/es_ES.json
=> Update translation strings as of 20190609T200038

findInterfaces/FindInterfacesModal.js
https://issues.folio.org/browse/UIORGS-88
=> UIORGS-88 Unable to search for interfaces

translations/ui-plugin-find-interface/ar.json, translations/ui-plugin-find-interface/ca.json, translations/ui-plugin-find-interface/da.json, translations/ui-plugin-find-interface/de.json, translations/ui-plugin-find-interface/en_GB.json, translations/ui-plugin-find-interface/en_SE.json, translations/ui-plugin-find-interface/en_US.json, translations/ui-plugin-find-interface/es.json, translations/ui-plugin-find-interface/es_419.json, translations/ui-plugin-find-interface/es_ES.json, translations/ui-plugin-find-interface/fr.json, translations/ui-plugin-find-interface/fr_FR.json, translations/ui-plugin-find-interface/hu.json, translations/ui-plugin-find-interface/it_IT.json, translations/ui-plugin-find-interface/pt_BR.json, translations/ui-plugin-find-interface/pt_PT.json, translations/ui-plugin-find-interface/zh_CN.json
=> Update translation strings as of 20190903T134424

translations/ui-plugin-find-interface/it_IT.json
=> Update translation strings as of 20190913T225241

translations/ui-plugin-find-interface/it_IT.json
=> Update translation strings as of 20190925T125755

translations/ui-plugin-find-interface/ru.json, translations/ui-plugin-find-interface/zh_TW.json
=> Update translation strings as of 20191014T135140

translations/ui-plugin-find-interface/ja.json
=> Update translation strings as of 20191028T205642

translations/ui-plugin-find-interface/he.json
=> Update translation strings as of 20191114T012425

translations/ui-plugin-find-interface/fr_FR.json, translations/ui-plugin-find-interface/it_IT.json
=> Update translation strings as of 20191122T140350

translations/ui-plugin-find-interface/fr_FR.json
=> Update translation strings as of 20191125T160504

translations/ui-plugin-find-interface/fr_FR.json
=> Update translation strings as of 20191203T022312

CHANGELOG.md, PULL_REQUEST_TEMPLATE.md, package.json
Create `UIPFINT` release
https://issues.folio.org/browse/UIPFINT-3
- Are the JIRAs under active development?  
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  
While it's helpful …
=> Release v1.3.0

translations/ui-plugin-find-interface/fr_FR.json
=> Update translation strings as of 20200117T173544

translations/ui-plugin-find-interface/it_IT.json
=> Update translation strings as of 20200202T214053

translations/ui-plugin-find-interface/ur.json
=> Update translation strings as of 20200210T220102

translations/ui-plugin-find-interface/ja.json
=> Update translation strings as of 20200413T183215

translations/ui-plugin-find-interface/ja.json
=> Update translation strings as of 20200421T180634

translations/ui-plugin-find-interface/zh_TW.json
=> Update translation strings as of 20200424T193712

translations/ui-plugin-find-interface/zh_TW.json
=> Update translation strings as of 20200428T150732

.gitignore, CHANGELOG.md, package.json
https://issues.folio.org/browse/UIPFINT-8 …
=> UIPFINT-8 Update to Stripes v4

CHANGELOG.md, findInterfaces/FindInterfacesContainer.js
https://issues.folio.org/browse/UIPFINT-6 …
=> UIPFINT-6 Sort order should be Name (A to Z)

package.json
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
=> Upgrade stripes v5

translations/ui-plugin-find-interface/hi_IN.json, translations/ui-plugin-find-interface/ko.json
=> Update translation strings as of 20200922T125348

translations/ui-plugin-find-interface/ja.json, translations/ui-plugin-find-interface/pl.json
=> Update translation strings as of 20200924T211627

CHANGELOG.md, findInterfaces/filterConfig.js
https://issues.folio.org/browse/UIPFINT-12 …
=> UIPFINT-12 Fix filter by type

CHANGELOG.md, findInterfaces/PluginFindInterfaces.js
https://issues.folio.org/browse/UIPFINT-14 …
=> UIPFINT-14 Add aria-label to select item checkbox

translations/ui-plugin-find-interface/ber.json
=> Update translation strings as of 20201109T135508

CHANGELOG.md, PERSONAL_DATA_DISCLOSURE.md
https://issues.folio.org/browse/UIPFINT-18 …
=> UIPFINT-18 Add personal data disclosure form

.eslintrc, package.json, test/bigtest/.eslintrc
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
=> revert bumping react

package.json
https://issues.folio.org/browse/UIPFINT-20 …
=> UIPFINT-20 Update stripes-cli to v2

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIPFINT-23 …
=> UIPFINT-23 increment stripes to v7

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIPFINT-33 …
=> UIPFINT-33 bump stripes to 8.0.0 for Orchid/2023-R1

.eslintrc, .github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md, findInterfaces/FindInterfacesContainer.test.js, findInterfaces/PluginFindInterfaces.test.js, jest.config.js, package.json
https://issues.folio.org/browse/UIPFINT-35
https://issues.folio.org/browse/UIPFINT-36
https://issues.folio.org/browse/UIPFINT-37
Upgrade `React` to `v18`, `Node` to `v18`, `react-intl` to `v6`. Include necessary components and test updates.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> UIPFINT-35 Upgrade `React` to `18` version

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml
Update `upload-artifact` version
=> Update Github workflow actions

CHANGELOG.md, findInterfaces/PluginFindInterfaces.js
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
=> UIPFINT-41 React v19: refactor away from default props for functional components

CHANGELOG.md, package.json
https://folio-org.atlassian.net/browse/UIPFINT-45
https://folio-org.atlassian.net/browse/UIPFINT-46
=> UIPFINT-45 UIPFINT-46 Migrate react-intl and stripes dependencies
